---
- name: Converge
  hosts: instance
  become: true

  tasks:
    - name: "Include variables from a file"
      include_vars:
        file: variables.yml

    - name: "Include dmitrii-ageev.openssl"
      include_role:
        name: dmitrii-ageev.openssl-gost
